const jobs = [
    {
        id: 1,
        title: "Software Development Engineer - Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "C++", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://www.amazon.jobs/en/jobs/2550508/software-development-engineer-intern",
        description: "Join our team for a challenging internship. You will be working on real projects and will have the opportunity to learn from experienced engineers. This is a great opportunity to start your career in software development."
    },
    {
        id: 2,
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C", "C++", "Java", "Python", "Database"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "3–5 LPA",
        applyUrl: "https://careers.infosys.com/jobdesc/RUP_JOB_DESC_11802.html",
        description: "As a Graduate Engineer Trainee, you will undergo our world-class training program and will be deployed on projects across various technologies. This is a launchpad for a successful career in the IT industry."
    },
    {
        id: 3,
        title: "Junior Backend Developer",
        company: "Swiggy",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Go", "Java", "Python", "REST APIs", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–18 LPA",
        applyUrl: "https://careers.swiggy.com/#/",
        description: "We are looking for a Junior Backend Developer to join our team. You will be responsible for developing and maintaining our backend services. If you are passionate about building scalable systems, this is the role for you."
    },
    // ... adding 57 more realistic jobs
    {
        id: 4,
        title: "Frontend Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["HTML", "CSS", "JavaScript", "React"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.flipkartcareers.com/#!/joblist",
        description: "This internship offers an opportunity to work on our consumer-facing products. You will learn how to build beautiful and performant user interfaces using the latest web technologies."
    },
    {
        id: 5,
        title: "Java Developer",
        company: "TCS",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring", "Hibernate", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "3–5 LPA",
        applyUrl: "https://www.tcs.com/careers/india",
        description: "We are hiring Java developers with 0-1 years of experience. You will be working on large-scale enterprise applications for our global clients. Strong core Java skills are a must."
    },
    {
        id: 6,
        title: "QA Intern",
        company: "Wipro",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "Automation Testing", "Selenium"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "₹15k/month Internship",
        applyUrl: "https://careers.wipro.com/opportunities",
        description: "As a QA intern, you will be responsible for ensuring the quality of our software products. You will learn about different testing methodologies and tools."
    },
    {
        id: 7,
        title: "Data Analyst Intern",
        company: "Accenture",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["SQL", "Excel", "Python", "Tableau"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k/month Internship",
        applyUrl: "https://www.accenture.com/in-en/careers",
        description: "This internship will give you exposure to the world of data analytics. You will be working with large datasets and will learn how to derive meaningful insights."
    },
    {
        id: 8,
        title: "Python Developer",
        company: "Razorpay",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "Django", "Flask", "AWS"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "10–18 LPA",
        applyUrl: "https://razorpay.com/careers/",
        description: "We are looking for a Python developer to join our payments team. You will be building and maintaining the APIs that power our payment gateway. Experience with Django or Flask is a plus."
    },
    {
        id: 9,
        title: "React Developer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Redux", "JavaScript", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://www.phonepe.com/careers/",
        description: "Join our team to build the next generation of financial products. We are looking for a React developer who is passionate about building great user experiences."
    },
    {
        id: 10,
        title: "Cloud Engineer",
        company: "IBM",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["AWS", "Azure", "GCP", "Kubernetes", "Docker"],
        source: "Indeed",
        postedDaysAgo: 8,
        salaryRange: "15-25 LPA",
        applyUrl: "https://www.ibm.com/in-en/employment/",
        description: "We are looking for an experienced Cloud Engineer to join our multi-cloud team. You will be responsible for designing, building, and maintaining our cloud infrastructure."
    },
    {
        id: 11,
        title: "Product Manager",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Product Management", "Agile", "Scrum", "JIRA"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20-30 LPA",
        applyUrl: "https://paytm.com/careers/",
        description: "As a Product Manager, you will be responsible for the entire product lifecycle, from ideation to launch. You will be working closely with engineers, designers, and business stakeholders."
    },
    {
        id: 12,
        title: "SDE-2",
        company: "CRED",
        location: "Remote",
        mode: "Remote",
        experience: "3-5",
        skills: ["Java", "Spring Boot", "Microservices", "System Design"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "30-50 LPA",
        applyUrl: "https://careers.cred.club/",
        description: "CRED is looking for experienced backend engineers to help us build the future of finance. If you have a strong background in system design and are passionate about building scalable and reliable systems, we would love to hear from you."
    },
    {
        id: 13,
        title: "DevOps Engineer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["CI/CD", "Jenkins", "Ansible", "Terraform"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "8-15 LPA",
        applyUrl: "https://www.zohocorp.com/careers/",
        description: "We are looking for a DevOps engineer to join our infrastructure team. You will be responsible for automating our build and release pipelines. Experience with CI/CD tools is a must."
    },
    {
        id: 14,
        title: "UI/UX Designer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Figma", "Sketch", "Adobe XD", "User Research"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10-18 LPA",
        applyUrl: "https://www.freshworks.com/company/careers/",
        description: "We are looking for a talented UI/UX designer to create amazing user experiences. You will be working on our suite of business software products. A strong portfolio is a must."
    },
    {
        id: 15,
        title: "Android Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kotlin", "Java", "Android SDK", "MVVM"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "12-20 LPA",
        applyUrl: "https://juspay.in/careers",
        description: "Join our mobile team to build the next generation of payment experiences on Android. We are looking for a developer who is passionate about clean code and great user experiences."
    },
    {
        id: 16,
        title: "Full Stack Developer",
        company: "TechieNest",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "Node.js", "MongoDB", "Express"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "8-12 LPA",
        description: "We are a fast-growing startup looking for a full stack developer to join our team. You will be working on all aspects of our product, from the frontend to the backend."
    },
    {
        id: 17,
        title: "Business Analyst",
        company: "Capgemini",
        location: "Pune",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Business Analysis", "Requirement Gathering", "Agile"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "9-16 LPA",
        description: "We are looking for a Business Analyst to join our consulting team. You will be working with our clients to understand their business needs and translate them into technical requirements."
    },
    {
        id: 18,
        title: "Data Scientist",
        company: "Cognizant",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Machine Learning", "Python", "R", "TensorFlow", "PyTorch"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15-25 LPA",
        description: "Join our team of data scientists to work on challenging problems in the areas of machine learning and artificial intelligence. A PhD or a Master's degree in a quantitative field is preferred."
    },
    {
        id: 19,
        title: "SAP Consultant",
        company: "SAP",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["SAP", "ABAP", "HANA"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "12-20 LPA",
        description: "We are looking for an experienced SAP consultant to join our professional services team. You will be responsible for implementing and supporting our SAP solutions for our clients."
    },
    {
        id: 20,
        title: "Oracle DBA",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Oracle", "SQL", "PL/SQL", "Database Administration"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "10-18 LPA",
        description: "We are looking for an experienced Oracle DBA to join our database administration team. You will be responsible for managing our large-scale Oracle databases."
    },
    {
        id: 21,
        title: "Network Engineer",
        company: "Dell",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Cisco", "Juniper", "Routing", "Switching"],
        source: "Indeed",
        postedDaysAgo: 8,
        salaryRange: "7-12 LPA",
        description: "We are looking for a Network Engineer to join our IT infrastructure team. You will be responsible for designing, implementing, and maintaining our corporate network."
    },
    {
        id: 22,
        title: "SDE Intern",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C#", ".NET", "Azure", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹45k/month Internship",
        applyUrl: "https://careers.microsoft.com/us/en/job/1550508/software-development-engineer-intern",
        description: "Our internship program offers a unique opportunity to work on cutting-edge technologies. You will be part of a team of experienced engineers and will have the chance to make a real impact on our products."
    },
    {
        id: 23,
        title: "Software Engineer - Fresher",
        company: "CodeZest",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "JavaScript", "React", "Node.js"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "5-7 LPA",
        description: "We are a product startup looking for freshers who are passionate about coding. You will get to work on our entire tech stack and will have a lot of learning opportunities."
    },
    {
        id: 24,
        title: "iOS Developer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Swift", "Objective-C", "iOS SDK", "MVVM"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12-20 LPA",
        applyUrl: "https://www.zomato.com/careers",
        description: "We are looking for an iOS developer to join our mobile team. You will be working on our consumer-facing app and will be responsible for building new features and improving the user experience."
    },
    {
        id: 25,
        title: "Technical Writer",
        company: "Postman",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Technical Writing", "API Documentation", "Markdown"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "8-14 LPA",
        applyUrl: "https://www.postman.com/company/careers/",
        description: "We are looking for a technical writer to create clear and concise documentation for our APIs. You will be working closely with our engineering team to ensure that our documentation is accurate and up-to-date."
    },
    {
        id: 26,
        title: "Security Engineer",
        company: "HackerRank",
        location: "Remote",
        mode: "Remote",
        experience: "3-5",
        skills: ["Application Security", "Network Security", "Penetration Testing"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "20-35 LPA",
        applyUrl: "https://www.hackerrank.com/careers",
        description: "We are looking for a security engineer to help us keep our platform safe and secure. You will be responsible for identifying and fixing security vulnerabilities in our applications and infrastructure."
    },
    {
        id: 27,
        title: "Marketing Intern",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Digital Marketing", "Social Media Marketing", "SEO"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://unacademy.com/careers",
        description: "Join our marketing team to learn the ropes of digital marketing. You will be working on our social media campaigns, SEO, and content marketing."
    },
    {
        id: 28,
        title: "Salesforce Developer",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Salesforce", "Apex", "Lightning", "Visualforce"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "8-15 LPA",
        description: "We are looking for a Salesforce developer to join our consulting practice. You will be working on implementing and customizing Salesforce for our clients."
    },
    {
        id: 29,
        title: "Game Developer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Unity", "C#", "Game Design"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "10-20 LPA",
        applyUrl: "https://www.dream11.com/careers",
        description: "We are looking for a game developer to join our team. You will be working on our fantasy sports platform and will be responsible for building new games and features."
    },
    {
        id: 30,
        title: "Systems Engineer",
        company: "Cisco",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Networking", "Python", "Linux"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "6-10 LPA",
        applyUrl: "https://www.cisco.com/c/en_in/about/careers.html",
        description: "We are looking for a Systems Engineer to join our technical support team. You will be responsible for troubleshooting and resolving complex technical issues for our customers."
    },
    {
        id: 31,
        title: "Associate consultant",
        company: "Bain & Company",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Consulting", "Analytics", "Problem Solving"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "18-25 LPA",
        applyUrl: "https://www.bain.com/careers/",
        description: "As an Associate Consultant, you will be working with our clients to solve their most pressing business problems. This is a fast-paced and challenging role that will provide you with a lot of learning opportunities."
    },
    {
        id: 32,
        title: "ML Engineer",
        company: "Ola",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Machine Learning", "Python", "Deep Learning", "NLP"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "15-25 LPA",
        applyUrl: "https://ola.com/careers/",
        description: "We are looking for an ML Engineer to join our team. You will be working on building and deploying machine learning models for our ride-hailing platform."
    },
    {
        id: 33,
        title: "Robotics Engineer",
        company: "GreyOrange",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Robotics", "C++", "ROS", "SLAM"],
        source: "LinkedIn",
        postedDaysAgo: 8,
        salaryRange: "12-22 LPA",
        applyUrl: "https://www.greyorange.com/careers/",
        description: "We are looking for a Robotics Engineer to join our team. You will be working on developing and deploying our autonomous mobile robots in warehouses."
    },
    {
        id: 34,
        title: "Embedded Systems Engineer",
        company: "Samsung",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Embedded Systems", "C", "C++", "RTOS"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "8-16 LPA",
        description: "We are looking for an Embedded Systems Engineer to join our mobile division. You will be working on developing and optimizing the software for our smartphones."
    },
    {
        id: 35,
        title: "VLSI Engineer",
        company: "Qualcomm",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["VLSI", "Verilog", "SystemVerilog", "UVM"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15-28 LPA",
        applyUrl: "https://www.qualcomm.com/company/careers",
        description: "We are looking for a VLSI Engineer to join our team. You will be working on the design and verification of our next-generation Snapdragon processors."
    },
    {
        id: 36,
        title: "Cyber Security Analyst",
        company: "PwC",
        location: "Kolkata",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Cyber Security", "SIEM", "Incident Response"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "7-14 LPA",
        description: "We are looking for a Cyber Security Analyst to join our risk advisory practice. You will be responsible for monitoring and responding to security incidents for our clients."
    },
    {
        id: 37,
        title: "Management Trainee",
        company: "HUL",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Management", "Marketing", "Sales"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "15-20 LPA",
        applyUrl: "https://www.hul.co.in/careers/",
        description: "Our management trainee program is a great way to start your career in the FMCG industry. You will get to work in different functions and will be groomed for a leadership role."
    },
    {
        id: 38,
        title: "Graphic Designer",
        company: "Canva",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Graphic Design", "Adobe Creative Suite", "Illustration"],
        source: "LinkedIn",
        postedDaysAgo: 9,
        salaryRange: "10-18 LPA",
        applyUrl: "https://www.canva.com/careers/",
        description: "We are looking for a talented graphic designer to join our team. You will be working on creating beautiful and engaging visuals for our product and marketing."
    },
    {
        id: 39,
        title: "Content Writer",
        company: "YourStory",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Content Writing", "Journalism", "Storytelling"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "4-6 LPA",
        applyUrl: "https://yourstory.com/careers",
        description: "We are looking for a content writer to join our editorial team. You will be writing stories about the Indian startup ecosystem. A passion for startups is a must."
    },
    {
        id: 40,
        title: "HR Intern",
        company: "Goldman Sachs",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Human Resources", "Recruitment", "Employee Engagement"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://www.goldmansachs.com/careers/students/programs/india/india-internship-program.html",
        description: "Our HR internship program will give you exposure to various aspects of human resources, from recruitment to employee engagement. This is a great opportunity to start your career in HR."
    },
    {
        id: 41,
        title: "Financial Analyst",
        company: "Morgan Stanley",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Financial Analysis", "Excel", "Valuation"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "12-20 LPA",
        applyUrl: "https://www.morganstanley.com/careers",
        description: "We are looking for a financial analyst to join our investment banking division. You will be working on mergers and acquisitions, and capital raising transactions."
    },
    {
        id: 42,
        title: "Research Intern",
        company: "NITI Aayog",
        location: "New Delhi",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Research", "Public Policy", "Economics"],
        source: "NITI Aayog",
        postedDaysAgo: 8,
        salaryRange: "Unpaid Internship",
        applyUrl: "https://www.niti.gov.in/career/internship",
        description: "Our internship program offers a unique opportunity to work on public policy issues. You will be working with our research team and will have the chance to contribute to our policy reports."
    },
    {
        id: 43,
        title: "Legal Intern",
        company: "Shardul Amarchand Mangaldas & Co",
        location: "New Delhi",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Law", "Corporate Law", "M&A"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://www.amsshardul.com/careers/",
        description: "Our internship program will give you exposure to various aspects of corporate law, from mergers and acquisitions to private equity. This is a great opportunity to start your career in law."
    },
    {
        id: 44,
        title: "Actuarial Analyst",
        company: "Aon",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Actuarial Science", "Statistics", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "6-10 LPA",
        description: "We are looking for an actuarial analyst to join our retirement solutions team. You will be working on valuing pension liabilities for our clients."
    },
    {
        id: 45,
        title: "Architect",
        company: "DLF",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Architecture", "AutoCAD", "Revit"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "10-18 LPA",
        description: "We are looking for an architect to join our design team. You will be working on designing our residential and commercial projects."
    },
    {
        id: 46,
        title: "Civil Engineer",
        company: "L&T",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Civil Engineering", "AutoCAD", "Staad Pro"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "4-7 LPA",
        description: "We are looking for a civil engineer to join our construction team. You will be working on our infrastructure projects, such as roads, bridges, and airports."
    },
    {
        id: 47,
        title: "Mechanical Engineer",
        company: "Tata Motors",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Mechanical Engineering", "CATIA", "Ansys"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "5-8 LPA",
        applyUrl: "https://www.tatamotors.com/careers/",
        description: "We are looking for a mechanical engineer to join our product development team. You will be working on designing and developing our next-generation vehicles."
    },
    {
        id: 48,
        title: "Electrical Engineer",
        company: "Siemens",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Electrical Engineering", "EPLAN", "PLC"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "5-9 LPA",
        description: "We are looking for an electrical engineer to join our automation team. You will be working on designing and implementing automation solutions for our clients."
    },
    {
        id: 49,
        title: "Chemical Engineer",
        company: "Reliance",
        location: "Jamnagar",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Chemical Engineering", "Aspen HYSYS", "Process Simulation"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "6-10 LPA",
        description: "We are looking for a chemical engineer to join our refinery team. You will be working on optimizing our refining processes."
    },
    {
        id: 50,
        title: "Biotechnologist",
        company: "Biocon",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Biotechnology", "Molecular Biology", "Cell Culture"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "4-7 LPA",
        applyUrl: "https://www.biocon.com/careers/",
        description: "We are looking for a biotechnologist to join our research and development team. You will be working on developing new biologics."
    },
    {
        id: 51,
        title: "Pharmacist",
        company: "Cipla",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Pharmacy", "Pharmacology", "Drug Development"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3-5 LPA",
        description: "We are looking for a pharmacist to join our clinical research team. You will be working on conducting clinical trials for our new drugs."
    },
    {
        id: 52,
        title: "Doctor",
        company: "Apollo Hospitals",
        location: "Chennai",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Medicine", "MBBS", "MD"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "15-25 LPA",
        applyUrl: "https://www.apollohospitals.com/careers/",
        description: "We are looking for a doctor to join our team of specialists. You will be responsible for providing high-quality medical care to our patients."
    },
    {
        id: 53,
        title: "Nurse",
        company: "Fortis Healthcare",
        location: "Delhi",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Nursing", "Patient Care", "BLS"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "3-6 LPA",
        description: "We are looking for a nurse to join our team of healthcare professionals. You will be responsible for providing compassionate care to our patients."
    },
    {
        id: 54,
        title: "Teacher",
        company: "Delhi Public School",
        location: "Delhi",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Teaching", "B.Ed", "CTET"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4-7 LPA",
        description: "We are looking for a teacher to join our team of educators. You will be responsible for creating a positive and engaging learning environment for our students."
    },
    {
        id: 55,
        title: "Professor",
        company: "IIT Bombay",
        location: "Mumbai",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Teaching", "Research", "PhD"],
        source: "IIT Bombay",
        postedDaysAgo: 10,
        salaryRange: "15-25 LPA",
        applyUrl: "https://www.iitb.ac.in/en/careers/faculty-recruitment",
        description: "We are looking for a professor to join our faculty. You will be responsible for teaching and conducting research in your area of expertise."
    },
    {
        id: 56,
        title: "Journalist",
        company: "The Hindu",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Journalism", "Writing", "Reporting"],
        source: "The Hindu",
        postedDaysAgo: 2,
        salaryRange: "5-8 LPA",
        description: "We are looking for a journalist to join our newsroom. You will be responsible for reporting on current events and writing articles for our newspaper."
    },
    {
        id: 57,
        title: "Lawyer",
        company: "AZB & Partners",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Law", "Corporate Law", "Litigation"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "12-20 LPA",
        description: "We are looking for a lawyer to join our corporate law practice. You will be working on mergers and acquisitions, and other corporate transactions."
    },
    {
        id: 58,
        title: "Chef",
        company: "Taj Hotels",
        location: "Mumbai",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Cooking", "Culinary Arts", "Menu Planning"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "8-15 LPA",
        applyUrl: "https://www.tajhotels.com/en-in/careers/",
        description: "We are looking for a chef to join our culinary team. You will be responsible for creating delicious and innovative dishes for our guests."
    },
    {
        id: 59,
        title: "Artist",
        company: "Christie's",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Art", "Painting", "Sculpture"],
        source: "LinkedIn",
        postedDaysAgo: 9,
        salaryRange: "Project-based",
        description: "We are looking for an artist to collaborate with us on our upcoming exhibition. You will have the opportunity to showcase your work to a global audience."
    },
    {
        id: 60,
        title: "Musician",
        company: "T-Series",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Music", "Singing", "Songwriting"],
        source: "T-Series",
        postedDaysAgo: 0,
        salaryRange: "Project-based",
        applyUrl: "https://www.tseries.com/contact-us",
        description: "We are looking for a musician to join our team of artists. You will have the opportunity to record your own music and perform at our events."
    }
];
